version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: interview-postgres
    environment:
      POSTGRES_USER: interview
      POSTGRES_PASSWORD: interview123
      POSTGRES_DB: waste_tracking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

